### ISSUE TITLE
Multiple transitions issue

### ISSUE THREAD

**Issue by jamesokelly** [Sa74/STCubeTransition#4]
I think there is an issue with multiple transitions occurring simultaneously because the contentView property gets overwritten by the latest call to translateView() and then the same contentView gets substituted into all the animationDidFinishWithView() delegate calls as opposed to each one getting called with its associated specific contentView

**Comment by Sa74** [comment]
Thanks for bringing it to my notice. I will look into this.

**Comment by Sa74** [comment]
Fixed in v1.4 release
