### ISSUE TITLE
In imageview 3D view is not seen proper

### ISSUE THREAD

**Issue by Rushabh5** [Sa74/STCubeTransition#6]
I have tried using UIImageview and changing the static image but it is not looking 3DCube so is there any way that i missed please find the attached [video](https://drive.google.com/file/d/1ZSg71bqHhLkHK1ovgy8JuYOzcS9G86lN/view?usp=share_link) and help me.

**Comment by Sa74** [comment]
Please share your code sample on this, I will be able to assist then.

**Comment by Rushabh5** [comment]
Thanks for your quick response.
PFA

[Demo Project Link](https://drive.google.com/file/d/1p89kPbWkAOSSla7U4_ee9-rIKuBnIqYc/view?usp=share_link)

**Comment by Sa74** [comment]
Your link contains this`STCubeTransition` project nothing more. I need to see your code on how you're trying to integrate this transition into your app.

**Comment by Rushabh5** [comment]
Manually I have added `STCubeTransition.swift` class. You can check this class. I have updated with UIImageview instead of UIView. 

`    init(_ fromView: UIImageView, toView: UIImageView, overlayView: UIImageView, completion: @escaping (_ displayView: UIImageView) -> ()) {`

**Comment by Rushabh5** [comment]
Hello @Sa74 ,

Have you found the code?

**Comment by Sa74** [comment]
Yes, you're trying to modify the original code from this library which is not required. I recommend you to create your own view and follow the instructions in ReadMe file to use this animation.
